[manager]
sort_dir_first = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
player = [
	{ run = 'mpv "$@"', orphan = true },
]
docviewer = [
	{ run = 'zathura "$@"', orphan = true },
]
imageviewer = [
	{ run = 'loupe "$@"', orphan = true },
]
open = [
	{ run = 'xdg-open "$@"', orphan = true },
]

[open]
rules = [
	{ mime = "application/pdf", use = "docviewer" },
	{ mime = "image/*", use = "imageviewer" },
	{ mime = "video/*", use = "player" },
]
